PRE_TIME_CONST = 'pre_time_const'
POST_TIME_CONST = 'post_time_const'
PHASE_SHIFT = 'phase_shift'
REFERENCE_FREQUENCY = 'ref_frequency'
BANDPASS_FILTER = 'bandpass_filter'

ALL_SETTINGS = [PRE_TIME_CONST, POST_TIME_CONST, PHASE_SHIFT, REFERENCE_FREQUENCY, BANDPASS_FILTER]