GAIN = 'gain'
PRE_TIME_CONST = 'pre_time_const'
POST_TIME_CONST = 'post_time_const'
PHASE_SHIFT = 'phase_shift'
REFERENCE_FREQUENCY = 'ref_frequency'
BANDPASS_FILTER = 'bandpass_filter'
LINE_FILTER = 'line'
LINE2_FILTER = 'line2'
DYNAMIC_RESERVE = 'dynamic_reserve'

SETTABLE_GAIN = 'settable_sensitivity'

SETTINGS_IN_GUI = [GAIN, PRE_TIME_CONST, POST_TIME_CONST, PHASE_SHIFT, REFERENCE_FREQUENCY, BANDPASS_FILTER]
LOWEST_AUTO_SETTABLE_GAIN_DEFAULT = 10
